# ===================================
spring.application.name=practicingspring

#Puerto

server.port=8081

#JDBC PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/PadelProject
spring.datasource.username=postgres
spring.datasource.password=openpg

#Hibernate configuration
#Cuando tengas las tablas creadas cambia en la linea de abajo el "update" por "none" 
#para que no se sobrescriban las tablas cadavez que ejecutas el servidor
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JWT configuration
jwt.secret=MySuperSecretKeyForPadelApiMustBeAtLeast32Bytes

#Swagger configuration

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationSorter=method