/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.padelproject;

import acceso.AccesoPadelProject;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author isard
 */
public class Reserva extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(Reserva.class.getName());
    private Map<Integer, Double> preciosPistas = new HashMap<>();
    private int idReserva = -1;
    private int idPista = -1;
    private boolean esCliente = false;

    
    
    

    /**
     * Creates new form Pista
     */
    public Reserva() {
        setResizable(false);
        initComponents();
        cargarUsuarios();
        cargarPistas();

        jSpinnerFecha.setModel(new SpinnerDateModel());
        JSpinner.DateEditor editor = new JSpinner.DateEditor(jSpinnerFecha, "dd/MM/yyyy");
        jSpinnerFecha.setEditor(editor);
        
        jSpinnerFecha.addChangeListener(e -> actualizarHorasDisponibles());

    }

    public Reserva(int idReserva) {
        setResizable(false);
        initComponents();
        this.idReserva = idReserva;
        cargarUsuarios();
        cargarPistas();
        cargarDatosReserva(idReserva);

        jSpinnerFecha.setModel(new SpinnerDateModel());
        JSpinner.DateEditor editor = new JSpinner.DateEditor(jSpinnerFecha, "dd/MM/yyyy");
        jSpinnerFecha.setEditor(editor);
        
        jSpinnerFecha.addChangeListener(e -> actualizarHorasDisponibles());

    }

    public Reserva(int id, boolean esPista) {
        setResizable(false);
        initComponents();
        cargarUsuarios();
        cargarPistas();

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel());
        JSpinner.DateEditor editor = new JSpinner.DateEditor(jSpinnerFecha, "dd/MM/yyyy");
        jSpinnerFecha.setEditor(editor);

        if (esPista) {
            this.idPista = id;
            cargarDatosPista(id);
            
            jSpinnerFecha.addChangeListener(e -> actualizarHorasDisponibles());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSpinnerFecha = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setText("Hora Inicio");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Selecciona hora inicio-", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00" }));
        jComboBox2.setToolTipText("");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Hora Fin");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione hora fin-", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio Total");

        jTextField1.setEditable(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestión Reservas");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reservar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado");

        jLabel6.setText("Identificador Usuario");

        jLabel7.setText("Identificador Pista");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione un estado-", "CONFIRMADA", "PEDIENTE ", "CANCELADA" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel8.setText("Identificador");

        jTextField2.setEditable(false);

        jLabel9.setText("Fecha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2))
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(497, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        calcularPrecio();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        calcularPrecio();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        calcularPrecio();
        actualizarHorasDisponibles();
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox2.getSelectedIndex() == 0 || jComboBox1.getSelectedIndex() == 0
                || jComboBox3.getSelectedIndex() == 0
                || jComboBox4.getSelectedIndex() == 0
                || jComboBox5.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Rellena todos los campos");
            return;
        }

        int idUsuario = Integer.parseInt(jComboBox4.getSelectedItem().toString().split(" - ")[0]);
        int idPista = Integer.parseInt(jComboBox5.getSelectedItem().toString().split(" - ")[0]);

        Map<String, Object> usuario = new HashMap<>();
        usuario.put("id", idUsuario);

        Map<String, Object> pista = new HashMap<>();
        pista.put("id", idPista);

        Date fechaSeleccionada = (Date) jSpinnerFecha.getValue();
        LocalDate fecha = fechaSeleccionada.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        if (fecha.isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "No puedes crear una reserva en una fecha pasada");
            return;
        }
        int hInicio = Integer.parseInt(jComboBox2.getSelectedItem().toString().split(":")[0]);
        int hFin = Integer.parseInt(jComboBox1.getSelectedItem().toString().split(":")[0]);
        String horaInicioCompleta = fecha + "T" + String.format("%02d", hInicio) + ":00:00";
        String horaFinCompleta = fecha + "T" + String.format("%02d", hFin) + ":00:00";

        Map<String, Object> reserva = new HashMap<>();
        reserva.put("usuario", usuario);
        reserva.put("pista", pista);
        reserva.put("horaInicio", horaInicioCompleta);
        reserva.put("horaFin", horaFinCompleta);
        reserva.put("estado", jComboBox3.getSelectedItem().toString().trim());
        reserva.put("precioTotal", Double.parseDouble(jTextField2.getText()));

        acceso.AccesoPadelProject acceso = new acceso.AccesoPadelProject();
        boolean creado = acceso.crear("/reservas", reserva);

         
        if (creado) {
            JOptionPane.showMessageDialog(this, "Reserva creada correctamente");
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            jComboBox4.setSelectedIndex(0);
            jComboBox5.setSelectedIndex(0);
            jTextField2.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error al crear la reserva, tramo horario/pista no disponible");
        }

       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (idReserva == -1) {
            JOptionPane.showMessageDialog(this, "No hay reserva seleccionada");
            return;
        }

        if (jComboBox2.getSelectedIndex() == 0 || jComboBox1.getSelectedIndex() == 0
                || jComboBox3.getSelectedIndex() == 0
                || jComboBox4.getSelectedIndex() == 0
                || jComboBox5.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Rellena todos los campos");
            return;
        }

        int idUsuario = Integer.parseInt(jComboBox4.getSelectedItem().toString().split(" - ")[0]);
        int idPista = Integer.parseInt(jComboBox5.getSelectedItem().toString().split(" - ")[0]);

        Map<String, Object> usuario = new HashMap<>();
        usuario.put("id", idUsuario);

        Map<String, Object> pista = new HashMap<>();
        pista.put("id", idPista);

        Date fechaSeleccionada = (Date) jSpinnerFecha.getValue();
        LocalDate fecha = fechaSeleccionada.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        int hInicio = Integer.parseInt(jComboBox2.getSelectedItem().toString().split(":")[0]);
        int hFin = Integer.parseInt(jComboBox1.getSelectedItem().toString().split(":")[0]);
        String horaInicioCompleta = fecha + "T" + String.format("%02d", hInicio) + ":00:00";
        String horaFinCompleta = fecha + "T" + String.format("%02d", hFin) + ":00:00";

        acceso.AccesoPadelProject accesoTemp = new acceso.AccesoPadelProject();
        Map reservaOriginal = accesoTemp.obtenerObjeto("/reservas/" + idReserva, Map.class);
        String fechaCreacion = reservaOriginal.get("fechaCreacion").toString();

        Map<String, Object> reserva = new HashMap<>();
        reserva.put("id", idReserva);
        reserva.put("fechaCreacion", fechaCreacion);
        reserva.put("usuario", usuario);
        reserva.put("pista", pista);
        reserva.put("horaInicio", horaInicioCompleta);
        reserva.put("horaFin", horaFinCompleta);
        reserva.put("estado", jComboBox3.getSelectedItem().toString().trim());
        reserva.put("precioTotal", Double.parseDouble(jTextField2.getText()));

        AccesoPadelProject acceso = new AccesoPadelProject();
        boolean modificado = acceso.crear("/reservas", reserva);

        if (modificado) {
            JOptionPane.showMessageDialog(this, "Reserva modificada correctamente");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar la reserva");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<Object> jComboBox1;
    private javax.swing.JComboBox<Object> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void cargarUsuarios() {
        acceso.AccesoPadelProject acceso = new acceso.AccesoPadelProject();
        List<Map> usuarios = acceso.obtenerLista("/usuarios", Map.class);

        jComboBox4.removeAllItems();
        jComboBox4.addItem("-Selecciona usuario-");

        for (Map u : usuarios) {
            jComboBox4.addItem(u.get("id") + " - " + u.get("nombre"));
        }
    }

    private void cargarPistas() {
        acceso.AccesoPadelProject acceso = new acceso.AccesoPadelProject();
        List<Map> pistas = acceso.obtenerLista("/pistas", Map.class);

        jComboBox5.removeAllItems();
        jComboBox5.addItem("-Selecciona pista-");

        for (Map p : pistas) {
            int id = (int) p.get("id");
            double precio = (double) p.get("precioHora");
            preciosPistas.put(id, precio); // guarda el precio
            jComboBox5.addItem(id + " - " + p.get("nombre"));
        }
    }

    private void calcularPrecio() {
        if (jComboBox2.getSelectedIndex() == 0 || jComboBox1.getSelectedIndex() == 0
                || jComboBox5.getSelectedIndex() == 0) {
            jTextField2.setText("");
            return;
        }

        int horaInicio = Integer.parseInt(jComboBox2.getSelectedItem().toString().split(":")[0]);
        int horaFin = Integer.parseInt(jComboBox1.getSelectedItem().toString().split(":")[0]);
        int horas = horaFin - horaInicio;

        if (horas <= 0) {
            jTextField2.setText("Hora inválida");
            return;
        }

        // Obtener precio de la pista seleccionada
        int idPista = Integer.parseInt(jComboBox5.getSelectedItem().toString().split(" - ")[0]);
        double precioPorHora = preciosPistas.getOrDefault(idPista, 0.0);
        double total = horas * precioPorHora;

        jTextField2.setText(String.valueOf(total));
    }

    private void cargarDatosReserva(int id) {
        AccesoPadelProject acceso = new AccesoPadelProject();
        Map reserva = acceso.obtenerObjeto("/reservas/" + id, Map.class);

        if (reserva == null) {
            return;
        }

        jTextField1.setText(reserva.get("id").toString());

        // Cargar estado
        String estado = reserva.get("estado").toString();
        for (int i = 0; i < jComboBox3.getItemCount(); i++) {
            if (jComboBox3.getItemAt(i).trim().equals(estado.trim())) {
                jComboBox3.setSelectedIndex(i);
                break;
            }
        }

        // Cargar usuario
        Map usuario = (Map) reserva.get("usuario");
        int idUsuario = (int) usuario.get("id");
        for (int i = 0; i < jComboBox4.getItemCount(); i++) {
            if (jComboBox4.getItemAt(i).toString().startsWith(idUsuario + " - ")) {
                jComboBox4.setSelectedIndex(i);
                break;
            }
        }

        // Cargar pista
        Map pista = (Map) reserva.get("pista");
        int idPista = (int) pista.get("id");
        for (int i = 0; i < jComboBox5.getItemCount(); i++) {
            if (jComboBox5.getItemAt(i).toString().startsWith(idPista + " - ")) {
                jComboBox5.setSelectedIndex(i);
                break;
            }
        }

        // Cargar horas
        String horaInicio = reserva.get("horaInicio").toString().split("T")[1].substring(0, 5);
        String horaFin = reserva.get("horaFin").toString().split("T")[1].substring(0, 5);

        for (int i = 0; i < jComboBox2.getItemCount(); i++) {
            if (jComboBox2.getItemAt(i).toString().equals(horaInicio)) {
                jComboBox2.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < jComboBox1.getItemCount(); i++) {
            if (jComboBox1.getItemAt(i).toString().equals(horaFin)) {
                jComboBox1.setSelectedIndex(i);
                break;
            }
        }
        jTextField2.setText(reserva.get("precioTotal").toString());
    }

    private void cargarDatosPista(int id) {
        acceso.AccesoPadelProject acceso = new acceso.AccesoPadelProject();
        Map pista = acceso.obtenerObjeto("/pistas/" + id, Map.class);

        if (pista == null) {
            return;
        }

        // Seleccionar la pista en el combobox y bloquearla
        for (int i = 0; i < jComboBox5.getItemCount(); i++) {
            if (jComboBox5.getItemAt(i).toString().startsWith(id + " - ")) {
                jComboBox5.setSelectedIndex(i);
                break;
            }
        }
        jComboBox5.setEnabled(false); // bloquear pista

        // Ocultar botón modificar
        jButton2.setVisible(false);

        // Poner el usuario que ha iniciado sesión y bloquearlo
        int idUsuarioActual = AccesoPadelProject.getIdUsuario();
        for (int i = 0; i < jComboBox4.getItemCount(); i++) {
            if (jComboBox4.getItemAt(i).toString().startsWith(idUsuarioActual + " - ")) {
                jComboBox4.setSelectedIndex(i);
                break;
            }
        }
        jComboBox4.setEnabled(false); // bloquear usuario
        jTextField1.setVisible(false); // ocultar el identificador de reserva
        jLabel8.setVisible(false);//ocultrar el jLabel8 del identificador
    }

    public void configurarModoCliente() {
        jComboBox4.setEnabled(false); // no puede cambiar el usuario
        jComboBox5.setEnabled(false); // no puede cambiar la pista
        jButton1.setVisible(false);   // ocultar botón añadir
    }
    
    private void actualizarHorasDisponibles() {
        
    if (!(jSpinnerFecha.getValue() instanceof Date)) return;
    if (jComboBox5.getSelectedIndex() == 0 || jSpinnerFecha.getValue() == null) return;

    int idPista = Integer.parseInt(jComboBox5.getSelectedItem().toString().split(" - ")[0]);
    Date fechaSeleccionada = (Date) jSpinnerFecha.getValue();
    LocalDate fecha = fechaSeleccionada.toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalDate();

    acceso.AccesoPadelProject acceso = new acceso.AccesoPadelProject();
    Map disponibilidad = acceso.obtenerObjeto(
        "/pistas/" + idPista + "/disponibilidad?fecha=" + fecha, Map.class);

    if (disponibilidad == null) return;

    List<String> horasLibres = (List<String>) disponibilidad.get("horasLibres");
    if (horasLibres == null || horasLibres.isEmpty()) return;

    // Extraer horas inicio únicas (parte izquierda de "08:00 - 09:00")
    Set<String> inicios = new LinkedHashSet<>();
    Set<String> fines = new LinkedHashSet<>();
    
    for (String tramo : horasLibres) {
        String[] partes = tramo.split(" - ");
        inicios.add(partes[0]); // "08:00"
        fines.add(partes[1]);   // "09:00"
    }

    // Actualizar combobox hora inicio
    jComboBox2.removeAllItems();
    jComboBox2.addItem("-Selecciona hora inicio-");
    for (String h : inicios) {
        jComboBox2.addItem(h);
    }

    // Actualizar combobox hora fin
    jComboBox1.removeAllItems();
    jComboBox1.addItem("-Seleccione hora fin-");
    for (String h : fines) {
        jComboBox1.addItem(h);
    }
}

}
